#要打印的基础语句，其中%s是占位符。
template: Hello, %s!
#默认引用时的名字，这里名字叫做Stranger
defaultName: Stranger

server:
 applicationConnectors:
    - type: http
      port: 9000
 adminConnectors:
    - type: http
      port: 9001